/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.File;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minh Tri
 */
public class NhapHangGUI extends javax.swing.JPanel {
	public String absolutePath = new File("").getAbsolutePath();

	/**
	 * Creates new form NewJPanel
	 */
	public NhapHangGUI() {
		initComponents();

	}

	public static void main(String[] argv) {
		JFrame f = new JFrame();
		NhapHangGUI a = new NhapHangGUI();
		f.getContentPane().setLayout(new BorderLayout());
		f.getContentPane().add(a, BorderLayout.CENTER);
		f.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel4 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		jPanel5.setAutoscrolls(true);
		jButton2 = new javax.swing.JButton();
		jButton2.setPreferredSize(new Dimension(120, 50));
		jButton1 = new javax.swing.JButton();
		jButton1.setPreferredSize(new Dimension(120, 50));
		jButton3 = new javax.swing.JButton();
		jButton3.setPreferredSize(new Dimension(120, 50));
		jButton4 = new javax.swing.JButton();
		jButton4.setPreferredSize(new Dimension(120, 50));
		jPanel1 = new javax.swing.JPanel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jTextField1 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jPanel3.setPreferredSize(new Dimension(270, 10));
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 14));
		jComboBox2 = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 14));
		jComboBox3 = new javax.swing.JComboBox<>();
		jPanel6 = new javax.swing.JPanel();
		FlowLayout flowLayout = (FlowLayout) jPanel6.getLayout();
		jPanel6.setBackground(Color.WHITE);
		jScrollPane2 = new javax.swing.JScrollPane();
		jScrollPane2.setPreferredSize(new Dimension(800, 600));
		jTable1 = new javax.swing.JTable();

		setToolTipText("");
		setLayout(new java.awt.BorderLayout());

		jPanel4.setLayout(new java.awt.BorderLayout());

		jPanel5.setForeground(new java.awt.Color(255, 255, 255));

		jButton2.setIcon(new javax.swing.ImageIcon(absolutePath + "/src/images/icons/add.png")); // NOI18N
		jButton2.setText("Thêm");
		jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jPanel5.add(jButton2);

		jButton1.setIcon(new javax.swing.ImageIcon(absolutePath + "/src/images/icons/information.png")); // NOI18N
		jButton1.setText("Chi Tiết");
		jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jPanel5.add(jButton1);

		jButton3.setIcon(new javax.swing.ImageIcon(absolutePath + "/src/images/icons/delete.png")); // NOI18N
		jButton3.setText("Hủy Phiếu");
		jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jPanel5.add(jButton3);

		jButton4.setIcon(new javax.swing.ImageIcon(absolutePath + "/src/images/icons/excel.png")); // NOI18N
		jButton4.setText("Xuất Excel");
		jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
		jPanel5.add(jButton4);

		jPanel4.add(jPanel5, BorderLayout.WEST);

		jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Item 3", "Item 4" }));
		jComboBox1.setPreferredSize(new java.awt.Dimension(72, 30));
		jPanel1.add(jComboBox1);

		jTextField1.setText("Tìm Kiếm");
		jTextField1.setPreferredSize(new java.awt.Dimension(180, 30));
		jPanel1.add(jTextField1);

		jButton5.setIcon(new javax.swing.ImageIcon(absolutePath + "/src/images/icons/reload.png")); // NOI18N
		jButton5.setText("Làm mới");
		jPanel1.add(jButton5);

		jPanel4.add(jPanel1, BorderLayout.EAST);

		add(jPanel4, BorderLayout.NORTH);
		jPanel2.setLayout(new BorderLayout(0, 0));

		jPanel3.setLayout(new java.awt.FlowLayout(FlowLayout.CENTER, 5, 10));

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel1.setText("Nhà Cung Cấp");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jLabel1.setPreferredSize(new Dimension(250, 20));
		jPanel3.add(jLabel1);

		jComboBox2.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox2.setPreferredSize(new java.awt.Dimension(220, 30));
		jPanel3.add(jComboBox2);

		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel2.setText("Nhân Viên Nhập");
		jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jLabel2.setPreferredSize(new java.awt.Dimension(250, 20));
		jPanel3.add(jLabel2);

		jComboBox3.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBox3.setPreferredSize(new java.awt.Dimension(220, 30));
		jPanel3.add(jComboBox3);

		jPanel2.add(jPanel3, BorderLayout.WEST);

		lblTSTin = new JLabel();
		lblTSTin.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblTSTin.setText("Từ Số Tiền(VNĐ)");
		lblTSTin.setPreferredSize(new Dimension(250, 20));
		lblTSTin.setHorizontalTextPosition(SwingConstants.CENTER);
		lblTSTin.setHorizontalAlignment(SwingConstants.LEFT);
		jPanel3.add(lblTSTin);

		textField = new JTextField();
		textField.setPreferredSize(new Dimension(300, 30));
		jPanel3.add(textField);
		textField.setColumns(23);

		lblnSTinvn = new JLabel();
		lblnSTinvn.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblnSTinvn.setText("Đến Số Tiền(VNĐ)");
		lblnSTinvn.setPreferredSize(new Dimension(250, 20));
		lblnSTinvn.setHorizontalTextPosition(SwingConstants.CENTER);
		lblnSTinvn.setHorizontalAlignment(SwingConstants.LEFT);
		jPanel3.add(lblnSTinvn);

		textField_1 = new JTextField();
		textField_1.setPreferredSize(new Dimension(300, 30));
		textField_1.setColumns(23);
		jPanel3.add(textField_1);

		jTable1.setModel(new DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null }, { null, null, null, null, null, null },
						{ null, null, null, null, null, null }, { null, null, null, null, null, null }, },
				new String[] { "STT", "M\u00E3 phi\u1EBFu", "Nh\u00E0 cung c\u1EA5p", "Nh\u00E2n vi\u00EAn",
						"Th\u1EDDi gian", "T\u1ED5ng ti\u1EC1n" }));
		jScrollPane2.setViewportView(jTable1);

		jPanel6.add(jScrollPane2);

		jPanel2.add(jPanel6, BorderLayout.CENTER);

		add(jPanel2, BorderLayout.CENTER);
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JComboBox<String> jComboBox2;
	private javax.swing.JComboBox<String> jComboBox3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private JLabel lblTSTin;
	private JTextField textField;
	private JLabel lblnSTinvn;
	private JTextField textField_1;
	// End of variables declaration

}
